# Generated by Django 3.1.2 on 2020-10-03 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_sending_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sending_delay',
            field=models.PositiveIntegerField(default=0, verbose_name='Задержка отправки письма (секунды)'),
        ),
    ]
