# Generated by Django 3.1.2 on 2020-10-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
    ]
